=== CAJ2/sage-databot/src/tags/schemas/variant_origins.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "origins": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "region_id": {
                        "type": "string"
                    },
                    "name": {
                        "$ref": "#/$defs/tr"
                    }
                },
                "minProperties": 1
            }
        },
        "emb_codes": {
            "type": "array",
            "items": {
                "type": "string",
                "minLength": 1
            }
        },
        "manufacturing": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "region_id": {
                        "type": "string"
                    },
                    "name": {
                        "$ref": "#/$defs/tr"
                    }
                },
                "minProperties": 1
            }
        },
        "stores": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "place_id": {
                        "type": "string"
                    },
                    "name": {
                        "$ref": "#/$defs/tr"
                    }
                },
                "minProperties": 1
            }
        }
    },
    "unevaluatedProperties": false,
    "$defs": {
        "tr": {
            "type": "object",
            "patternProperties": {
                "^[a-z]{2}-?([A-Z]{2})?(;[a-z=]+)*$": {
                    "type": "string"
                }
            },
            "minProperties": 1,
            "unevaluatedProperties": false
        }
    }
}

=== CAJ2/sage-databot/src/tags/schemas/variant_origins_test.json
{
  "origins": [
    {
      "region_id": "AbCd123",
      "name": {
        "en": "Test Name",
        "sv": "Test Namn"
      }
    }
  ],
  "emb_codes": [
    "AbCd123"
  ],
  "manufacturing": [
    {
      "region_id": "AbCd123",
      "name": {
        "en": "Test Name",
        "sv": "Test Namn"
      }
    }
  ],
  "stores": [
    {
      "place_id": "AbCd123",
      "name": {
        "en": "Test Name",
        "sv": "Test Namn"
      }
    }
  ]
}
